/*

 * This Java source file was generated by the Gradle 'init' task.
 */
package data;
import org.junit.Test;
import org.junit.runner.RunWith;

import data.Invoice;
import data.InvoiceDAO;
import static org.junit.Assert.*;

import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.class)
public class InvoiceDAOTest {

	@Mock
	private InvoiceDAO invoiceDao;
	@Test
	public void testGet(){
		System.out.println(invoiceDao);
		long id = 1;
		Invoice invoice = new Invoice(1, 20.0, "samer");
		when(invoiceDao.get(id)).thenReturn(invoice);
		
		assertEquals(invoiceDao.get(id), invoice);
	}
		
}
